# Generated by Django 3.2.12 on 2023-12-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subpack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('price', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('night', models.CharField(max_length=10)),
            ],
        ),
    ]
