# Generated by Django 3.2.12 on 2023-11-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sections',
            new_name='section',
        ),
    ]
